// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlnmYPhghMEXKPzTphXSnWGvN5s7yt0iQ',
    appId: '1:241229522100:web:4b1737592cf929dfd163e1',
    messagingSenderId: '241229522100',
    projectId: 'interstx',
    authDomain: 'interstx.firebaseapp.com',
    storageBucket: 'interstx.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc1d4-ksjuF9LOnSvQ4as8T0K_ZMy4AAE',
    appId: '1:241229522100:android:c93d716972a7ecb7d163e1',
    messagingSenderId: '241229522100',
    projectId: 'interstx',
    storageBucket: 'interstx.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuHhN5wYD4jMNJScA_zVX0F64lfd0tINk',
    appId: '1:241229522100:ios:ae5b40cbd891ffd6d163e1',
    messagingSenderId: '241229522100',
    projectId: 'interstx',
    storageBucket: 'interstx.firebasestorage.app',
    iosBundleId: 'com.example.smartInterestx',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDlnmYPhghMEXKPzTphXSnWGvN5s7yt0iQ',
    appId: '1:241229522100:web:a097cbd46d05bd53d163e1',
    messagingSenderId: '241229522100',
    projectId: 'interstx',
    authDomain: 'interstx.firebaseapp.com',
    storageBucket: 'interstx.firebasestorage.app',
  );
}
