// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB6uB4whoPI5RJQ0SydytkzvB8IRkommI',
    appId: '1:554233250714:web:949b88df10bffc223bf023',
    messagingSenderId: '554233250714',
    projectId: 'real-time-chat-dec60',
    authDomain: 'real-time-chat-dec60.firebaseapp.com',
    storageBucket: 'real-time-chat-dec60.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB28nrs823HG6xPepaSljo5W_qaGAB57RQ',
    appId: '1:554233250714:android:1b5e99fc6bc5d0ce3bf023',
    messagingSenderId: '554233250714',
    projectId: 'real-time-chat-dec60',
    storageBucket: 'real-time-chat-dec60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpaP80qcf9Bqqa8EPD0SZcLsGS6KMO1HE',
    appId: '1:554233250714:ios:ab6742238c7bc7183bf023',
    messagingSenderId: '554233250714',
    projectId: 'real-time-chat-dec60',
    storageBucket: 'real-time-chat-dec60.firebasestorage.app',
    iosBundleId: 'com.example.realTimeChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpaP80qcf9Bqqa8EPD0SZcLsGS6KMO1HE',
    appId: '1:554233250714:ios:ab6742238c7bc7183bf023',
    messagingSenderId: '554233250714',
    projectId: 'real-time-chat-dec60',
    storageBucket: 'real-time-chat-dec60.firebasestorage.app',
    iosBundleId: 'com.example.realTimeChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDB6uB4whoPI5RJQ0SydytkzvB8IRkommI',
    appId: '1:554233250714:web:1b33fc50fa988aec3bf023',
    messagingSenderId: '554233250714',
    projectId: 'real-time-chat-dec60',
    authDomain: 'real-time-chat-dec60.firebaseapp.com',
    storageBucket: 'real-time-chat-dec60.firebasestorage.app',
  );
}
